first_app/urls.py
from django.urls import path,re_path
from .views import home,share

app_name = 'fist_app'

urlpatterns = [
    path('',home,name='home'),
    path('<str:ref_id>',share,name='share')
]

lwc/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('first_app.urls',namespace='first_app')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

first_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Join(models.Model):
    email      = models.EmailField()
    firend     = models.ForeignKey("self",related_name='referral',null=True,blank=True,on_delete=models.SET_NULL)
    ref_id     = models.CharField(max_length=120, null=True)
    ip_address = models.CharField(max_length=120,null=True)
    timestamp  = models.DateTimeField(auto_now_add=True)
    updated    = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.email
    
    def get_absolute_url(self):
        return reverse("first_app:share",kwargs={'ref_id':self.ref_id})

first_app/forms.py
from django import forms
from .models import Join

class EmailForm(forms.ModelForm):
    class Meta:
        model = Join
        fields = ['email']
    
    

first_app/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.urls import reverse
from .forms import EmailForm
from .models import Join
import uuid
from lwc.middleware import ReferMiddleware
# Create your views here.

def get_ip(request):
    try:
        x_forward = request.META.get("HTTP_X_FORWARDED_FOR")
        if x_forward:
            ip = x_forward.split(",")[0]
        else:
            ip = request.META.get("REMOTE_ADDR")
    except:
        ip = ""
    return ip

def get_ref_id():
    ref_id =  str(uuid.uuid4())[:11].replace('-','').lower()
    try:
        id_exists = Join.objects.get(ref_id=ref_id)
        get_ref_id()
    except:
        return ref_id


def share(request,ref_id):
    join_obj = get_object_or_404(Join,ref_id=ref_id)
    count = join_obj.referral.all().count()
    ref_url = "http://127.0.0.1:8000/?ref={}".format(join_obj.ref_id)
    context = {
        'ref_id':join_obj.ref_id,
        'count':count,
        'ref_url':ref_url
    }
    temaplate = 'share.html'
    return render(request,temaplate,context)


def home(request):
    try:
        join_id = request.session['join_id_ref']
        obj = Join.objects.get(id=join_id)
    except:
        obj = None

    form = EmailForm(request.POST or None)
    if form.is_valid():
        new_join = form.save(commit=False)
        email = form.cleaned_data.get('email')
        new_join_old, created = Join.objects.get_or_create(email=email)
        if created:
            new_join_old.ref_id = get_ref_id()
            if not obj == None:
                new_join_old.firend = obj
            new_join_old.ip_address = get_ip(request)
            new_join_old.save()
        return HttpResponseRedirect('/{ref_id}'.format(ref_id=new_join_old.ref_id))
    else:
        form = EmailForm()
    context = {
        'form':form
    }
    return render(request,'index.html',context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">
        
    
        <title>{% block title %}{% endblock %}</title>
    
        <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/jumbotron/">
        <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" />
    
        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">


      </head>
<body>
    {% include 'navbar.html' %}

    {% block content %}
    {% endblock %}
    
   <!-- Optional theme -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        {% block jquery %}
        {% endblock %}
    });
</script>
</body>
</html>

templates/footer.html
<footer class="container">
    <p>© Company 2017-2018</p>
</footer>

templates/index.html
{% extends 'base.html' %} {% block title %} Landing Page -- Home{% endblock %}{% load crispy_forms_tags %}
{% block content %}

<main role="main">
  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron" style="margin-top: 50px;">
    <div class="container">
      <div class="row">
        <h1 class="display-3">Join Our Course</h1>
        <p>
          This is a template for a simple marketing or informational website. It
          includes a large callout called a jumbotron and three supporting
          pieces of content. Use it as a starting point to create something more
          unique.
        </p>
        <div class="col-md-4">
          <form method="POST">
            {% csrf_token %} {{form|crispy}}
            <button type="submit" class="btn btn-primary">Get Started >></button>
          </form>
        </div>
      </div>
    </div>
  </div>

  <!-- /container -->
</main>

{% endblock %}

templates/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'first_app:home' %}">BoringDevStuff</a>
    </div>

  </div>
</nav>

templates/share.html
{% extends 'base.html' %} {% block title %} Landing Page -- Share{% endblock%}{%load static %}
{% block jquery %}

$signUpCount = {{count}};

//$(".progress-bar").css("width","80%"),.attr("aria-valuenow","80%").text("80%")

function completedBlock(progressBarId){
  $(progressBarId).css("width","100%").attr("aria-valuenow","100%").text("Completed");
};

function setNewPerc(progressBarId, percentNum, newText){
  $(progressBarId).css("width", percentNum + "%").attr("aria-valuenow", percentNum).text(newText);
};

if ($signUpCount == 0) {

}
else if ($signUpCount > 0 && $signUpCount < 25){
  $newPercent = $signUpCount/25 * 100;
  setNewPerc("#count25", $newPercent, "Number of Friends: " + $signUpCount)

}
else if ($signUpCount >=25 && $signUpCount < 50){
  completedBlock("#count25")

  $newCount = $signUpCount - 25;
  $newPercent = $newCount/(50-25) * 100;
  setNewPerc("#count50", $newPercent, "Number of Friends: " + $signUpCount)
}
else if ($signUpCount >=50 && $signUpCount < 75){
  completedBlock("#count25")
  completedBlock("#count50")

  $newCount = $signUpCount - 50;
  $newPercent = $newCount/(75-25) * 100;
  setNewPerc("#count75", $newPercent, "Number of Friends: " + $signUpCount)
}
else if ($signUpCount >=75 && $signUpCount < 100){
  completedBlock("#count25")
  completedBlock("#count50")
  completedBlock("#count75")

  $newCount = $signUpCount - 75;
  $newPercent = $newCount/(100-75) * 100;
  setNewPerc("#count100", $newPercent, "Number of Friends: " + $signUpCount)
}
else {
  $("#count25").css("width","100%").attr("aria-valuenow","100%").text("Completed");
  $("#count50").css("width","100%").attr("aria-valuenow","100%").text("Completed");
  $("#count75").css("width","100%").attr("aria-valuenow","100%").text("Completed");
  $("#count100").css("width","100%").attr("aria-valuenow","100%").text("Completed");
}
{% endblock %}



<style>
  .well {
    background-color: white;
  }
</style>
{% block content %}
<div class="jumbotron" style="margin-top: 50px;">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <img
          src="{% static 'asset/images/rocket.jpg' %}"
          height="500px"
          width="550px"
        />
      </div>
      <div class="col-md-6" style='text-align:center;'>
        <i class="fa fa-share-alt fa-5x"></i>
        <h1 class="display-3" style="margin: 20px;">
          Invite Friends & Earn Rewards
        </h1>
        <br />
          Share your unique link below via Email, Facebook, Twitter,<br />
          &nbsp;&nbsp;Reddit,
          or Linkedin to earn rewards from <br />
          &nbsp;&nbsp;BoringDevStuff.com
        </p>
        <div class="well" style="color: black; text-align: center;">
          {{ref_url}}
        </div>
        <div style="margin-left:160px;">
          <a href="https://www.facebook.com/sharer/sharer.php?u={{ref_url}}">
            <i class="fa fa-facebook-square fa-4x" style="color: #3b5998;"></i>
          </a>

          <a href="https://twitter.com/home?status=I'm%20going%20to%20learn%20to%20Code...%20Come%20build%20an%20web%20apsp%20with%20me!%20%23CFE%20and%20@justinmitchel%20{{ref_url}}">
            <i class="fa fa-twitter-square fa-4x" style="color: #4099ff;"></i>
          </a>

          <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ref_url}}&title=Be%20first%20%7C%20Join%20Our%20Course%20for%20Entrepreneurs&summary=Join%20for%20Entrepreneurs%20is%20a%20project-based%20programming%20course%20for%20non-technical%20founders.%20We'll%20learn%20how%20to%20build%20iOS%20apps%20from%20scratch%20using%20Apple's%20new%20programming%20language:%20Swift.%20Be%20first%20and%20learn%20with%20me!&source={{ref_url}}">
            <i class="fa fa-linkedin-square fa-4x" style="color: #007bb6;"></i>
          </a>
          
          <a href="http://www.reddit.com/submit?url={{ref_url}}&title=Unlock%20to%20Learn%20Swift%20for%20Free!%20By%20Swift%20for%20Entrepreneurs.%20Made%20for%20Non%20Techincals.">
            <i class="fa fa-reddit-square fa-4x" style="color: #900020;"></i>
          </a>
          

          <a href='https://plus.google.com/share?url={{ref_url}}'>
            <i class="fa fa-google-plus-square fa-4x" style="color: #d34836;"></i>
          </a>
          
        </div>
      </div>
    </div>
  </div>
</div>
<br />
<br />
<div class='container' style="text-align:center;">
  Joined number is: {{ count }}<br/>
  
<div class="row">
	<div class="col-sm-3">
	<h3>25 Joined</h3>
		<div class="progress">
			  <div class="progress-bar" id="count25" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
			   0%
			  </div>
		</div>
	</div>
	<div class="col-sm-3">
	<h3>50 Joined</h3>
		<div class="progress">
			  <div class="progress-bar" id="count50" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
			   0%
			  </div>
		</div>
	</div>
	<div class="col-sm-3">
	<h3>75 Joined</h3>
		<div class="progress">
			  <div class="progress-bar" id="count75" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
			   0%
			  </div>
		</div>
	</div>
	<div class="col-sm-3">
	<h3>100 Joined</h3>
		<div class="progress">
			  <div class="progress-bar" id="count100" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
			   0%
			  </div>
		</div>
	</div>
</div>

{% include 'footer.html' %}


{% endblock %}